#!/usr/bin/env perl
use 5.010;
use strict;
use XML::LibXML;
use XML::Liberal;

my $p = XML::Liberal->new;

my $xpath = XML::LibXML::XPathContext->new;
$xpath->registerNs( atom => 'http://www.w3.org/2005/Atom' );

my $first = $p->parse_file( shift @ARGV );
my ( $last_entry ) = $xpath->findnodes( '/atom:feed/atom:entry[last()]/following-sibling::text()[1]', $first );

while ( @ARGV ) {
	my $next = $p->parse_file( shift @ARGV );
	$first->documentElement->insertBefore( $_, $last_entry )
		for $xpath->findnodes( '/atom:feed/atom:entry|/atom:feed/atom:entry/preceding-sibling::text()[1]', $next );
}

$first->toFH( \*STDOUT );
