#!/usr/bin/perl
use strict;
use warnings;

use Getopt::Std;
use URI ();

getopts( 'sw:t:', \my %opt );

die "usage: $0 [-s [-w columns]] [-t mimetype] [file]\n" if @ARGV > 1;
my $width = $opt{'s'} && ( $opt{'w'} || 72 );
my $type = $opt{'t'};

my ( $filename ) = @ARGV;

my $data = do { local $/; <> };

$type ||= do {
	require File::Type;
	my $ft = File::Type->new();
	defined $filename ? $ft->checktype_filename( $filename ) : $ft->checktype_contents( $data );
};

my $str = do {
	my $u = URI->new( 'data:' );
	$u->media_type( $type );
	$u->data( $data );
	$u->as_string;
};

$\ = $, = "\n";

print $width
	? map { /\A(.*?,)/gcs, /\G(.{1,$width})/gs } $str
	: $str;
